- task: AzureResourceGroupDeployment@2
  inputs:
    ConnectedServiceName: 'Azure-infra-service-connection'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Temasek-Devops-Rg'
    location: 'Southeast Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/vikranthsuravarapu/Azure-Storage-/blob/master/Storage.Accounttemplate.json'
    csmParametersFileLink: 'https://github.com/vikranthsuravarapu/Azure-Storage-/blob/master/Storage.Account.Parameters.json'